service: mightyserverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessAWS
  #  stage: dev
  region: eu-central-1
  environment:
    USER_TABLE: ${self:custom.usersTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - ses:*
        - SNS:Publish
      Resource: '*'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  usersTable: usersTable

functions:
  dynamoTrigger:
    handler: lambdas/endpoints/dynamoTrigger.dynamoTrigger
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - DynamoDBTable
              - StreamArn
  sendEmail:
    handler: lambdas/endpoints/sendEmail.sendEmail
    events:
      - sns: sendWel
      - http:
          path: send
          method: post
          cors: true
  queryUsers:
    handler: lambdas/endpoints/query.queryUsers
    events:
      - http:
          path: users
          method: get
          cors: true
      - http:
          path: users
          method: post
          cors: true
      - http:
          path: users/{id}
          method: get
          cors: true
      - http:
          path: users/{id}
          method: put
          cors: true
      - http:
          path: users/{id}
          method: delete
          cors: true
      - http:
          path: signup
          method: post
          cors: true
      - http:
          path: login
          method: post
          cors: true

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
